massUploadValidationSchema = {
  "sectionNameMapping" : {
    'company information' : 'section_1',
    'employee commuting' : 'section_2',
    'business travel' : 'section_3',
    'energy' : 'section_4',
    'fuels' : 'section_5',
    'detailed carbon' : 'section_6',
  },
  "headerMapping": {
    "section_1": ["company information", "custom type"],
    "section_2": [
      "employee commuting",
      "sub-category",
      "type",
      "sub-type",
      "unit",
      "cost/unit",
      "driver name",
      "registration",
      "is reporting",
    ],
    "section_3": [
      "business travel",
      "sub-category",
      "type",
      "sub-type",
      "unit",
      "cost/unit",
      "driver name",
      "registration",
      "is reporting",
    ],
    'section_4': [
      "energy",
      "sub-category",
      "type",
      "sub-type",
      "unit",
      "cost/unit",
      "workplace(office/home)",
      "meter name",
      "meter number",
    ],
    'section_5': [
      "fuels",
      "sub-category",
      "type",
      "sub-type",
      "unit",
      "cost/unit",
      "workplace(office/home)",
      "custom name",
      "carbon factor",
    ],
    "section_6": [
      "detailed carbon",
      "sub-category",
      "type",
      "sub-type",
      "unit",
      "cost/unit",
      "co2/unit kg",
    ],
  },
  "sheetMapping": {
    "company": { "scope" : None, "category" : None, "sectionPointer" : ['section_1'] },
    "scope 1 - category 1": { "scope" : 1, "category" : "companyFacilities", "sectionPointer" : ['section_4', 'section_5'] },
    "scope 1 - category 2": { "scope" : 1, "category" : "companyVehicles", "sectionPointer" : ['section_3'] },
    "company vehicles": { "scope" : 1, "category" : "companyVehicles", "sectionPointer" : ['section_3'] },
    "scope 2 - category 1": { "scope" : 2, "category" : "purchasedEnergy", "sectionPointer" : ['section_4', 'section_5']  },
    "scope 2 - category 2": { "scope" : 2, "category" : "generatedElectricity", "sectionPointer" : ['section_4'] },
    "scope 3 - category 1": { "scope" : 3, "category" : "purchasedGoodsAndServices", "sectionPointer" : ['section_6'] },
    "scope 3 - category 2": { "scope" : 3, "category" : "capitalGoods", "sectionPointer" : ['section_6'] },
    "scope 3 - category 3": { "scope" : 3, "category" : "fuelEnergyActivities", "sectionPointer" : ['section_4', 'section_5', 'section_6'] },
    "scope 3 - category 4": { "scope" : 3, "category" : "upstreamTransportationDistribution", "sectionPointer" : ['section_6'] },
    "scope 3 - category 5": { "scope" : 3, "category" : "wasteGeneratedFromOperations", "sectionPointer" : ['section_6'] },
    "scope 3 - category 6": { "scope" : 3, "category" : "businessTravel", "sectionPointer" : ['section_3', 'section_6'] },
    "scope 3 - category 7": { "scope" : 3, "category" : "employeeTravel", "sectionPointer" : ['section_2', 'section_6'] },
    "scope 3 - category 8": { "scope" : 3, "category" : "upstreamLeasedAssets", "sectionPointer" : ['section_6'] },
    "scope 3 - category 9": { "scope" : 3, "category" : "downstreamTransportation", "sectionPointer" : ['section_6'] },
    "scope 3 - category 10": { "scope" : 3, "category" : "processingOfSoldProducts", "sectionPointer" : ['section_6'] },
    "scope 3 - category 11": { "scope" : 3, "category" : "useOfSoldProducts", "sectionPointer" : ['section_6'] },
    "scope 3 - category 12": { "scope" : 3, "category" : "endoflifeTreatmentOfSoldProducts", "sectionPointer" : ['section_6'] },
    "scope 3 - category 13": { "scope" : 3, "category" : "downstreamLeasedAssets", "sectionPointer" : ['section_6'] },
    "scope 3 - category 14": { "scope" : 3, "category" : "franchises", "sectionPointer" : ['section_6'] },
    "scope 3 - category 15": { "scope" : 3, "category" : "investments", "sectionPointer" : ['section_6'] },
  },
}